services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sunmail-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: SunMailDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - net

  # C++ Bloom Filter Server
  server:
    build:
      context: ./src/cpp
      dockerfile: Dockerfile.server
    container_name: bloomfilter-server
    networks:
      - net
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - ARRAY_SIZE=${ARRAY_SIZE}
      - HASH_REPEATS=${HASH_REPEATS}
    env_file:
      - ./src/cpp/.env
    entrypoint:
      - sh
      - -c
      - ./build/app $PORT $ARRAY_SIZE $HASH_REPEATS

  # Node.js API
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: node-api
    depends_on:
      - server
      - mongodb
    networks:
      - net
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=docker
    entrypoint:
      - sh
      - -c
      - node src/gmail.js

  # React Client
  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - net
    depends_on:
      - api
    command: npm start

volumes:
  mongodb_data:
  data_volume:

networks:
  net:
    driver: bridge
